In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('pulsars/ATNF_PulsarCatalogue.csv')

print(f"Total: {len(df)}")

FileNotFoundError: [Errno 2] No such file or directory: '/ATNF_PulsarCatalogue.csv'

In [ ]:
df['AGE'] = pd.to_numeric(df['AGE'].replace('*', np.nan), errors='coerce')

age_pulsars = df.dropna(subset=['AGE'])
print(f"Pulsars with age: {len(age_pulsars)}")

Pulsars with age: 2855

In [ ]:
df_young = age_pulsars.sort_values(by='DIST', ascending=True)

close_pulsars = df_young[df_young['AGE'] < 100000]

columns = ['NAME', 'AGE', 'DIST', 'ASSOC', 'PMTOT', 'VTRANS']

close_pulsars[columns]

NameError: name 'age_pulsars' is not defined

In [ ]:
df['DIST'] = pd.to_numeric(df['DIST'].replace('*', np.nan), errors='coerce')

close_pulsars = df[df['DIST'] < 1.0]
close_pulsars[['NAME', 'DIST', 'AGE']].sort_values(by='DIST')

            NAME   DIST           AGE
216   J0437-4715  0.157  1.590000e+09
3043  J1856-3754  0.160  3.760000e+06
4243  J2144-3933  0.160  2.720000e+08
367   J0633+1746  0.190  3.420000e+05
1964    B1742-30  0.200  5.460000e+05
...          ...    ...           ...
161     B0320+39  0.940  7.560000e+07
4138    B2045-16  0.950  2.840000e+06
913     B1322+83  0.960  1.870000e+07
4306  J2234+0611  0.971  4.720000e+09
4037    B2016+28  0.980  5.970000e+07

[74 rows x 3 columns]

In [ ]:
p = df[df['NAME'] == 'J0720-3125']
p

,NAME,PSRJ,PMRA,PMDEC,PX,BINARY,DIST,ASSOC,PSR,AGE,PMTOT,VTRANS
409,J0720-3125,J0720-3125,-93.9,52.8,2.8,*,0.4,"XRS:RX_J0720.4-3125,OPT:[kva07]","XINS,NRAD",1900000.0,107.7,204.29